- .travis.yml
- AUTHORS
- CONTRIBUTING.rst
- LICENSE.txt
- MANIFEST.in
- README.md
- README.rst
- auth_backends/backends.py
- auth_backends/pipeline.py
- auth_backends/tests/test_backends.py
- auth_backends/tests/test_pipeline.py
- manage.py
- requirements.txt
- setup.py
- test.sh
- tests/settings.py
This includes pared-down unit tests from analytics-dashboard. My next steps after merging this will be preparing the package for distribution on PyPI and then retrofitting the analytics dashboard to use it. The package is currently called `auth_backends`, but I'm thinking we'll want the package distributed on PyPI to be named something like `edx-auth-backends`. I'll speak with @nedbat about the details.
@clintonb, could you please review this?
@stephensanchez and @dianakhuang, FYI.
> Pull in custom backend and pipeline steps from analytics-dashboard

- .travis.yml
As per [TE-751](https://openedx.atlassian.net/browse/TE-751). @stephensanchez, could I get a thumb on this, when you're able?
> Prevent Travis from performing two builds per PR

- README.rst
- requirements.txt
- setup.py
The released version of python-social-auth was just updated to 0.2.2. This PR updates the dependencies for the edx-auth-backends package to include the new version.
@stephensanchez, when you have a moment, can I get a quick thumb? I'll release a new version of the package on PyPI once this is in.
> Require PSA from PyPI

- setup.py
I stumbled across your setup.py, and noticed a few funky things.  Everything was valid, but kinda quirky and not idiomatic.
so, I:
- removed the exec() call and just imported __version__
- removed the 'read()' function and just read the file contents from within a context manager.
happy hacking,
-Corey
> fixed up setup.py

- HISTORY.rst
- auth_backends/_version.py
- requirements.txt
- setup.py
Upgrading PSA to 0.2.3 fixes a PyJWT dependency conflict when using auth-backends with other projects which have upgraded to PyJWT >= 1.0.0. I'll tag and create a new release of auth-backends once this lands.
@clintonb or @nasthagiri 
@feanil FYI
> Upgrade PSA to 0.2.3

- setup.py
> Fix setup.py to exclude auth_backends/tests from installation

- auth_backends/_version.py
- auth_backends/backends.py
- auth_backends/tests/test_backends.py
We need to be able to configure SOCIAL_AUTH settings per site.
Related PR:
https://github.com/edx/ecommerce/pull/543
> WL-286 Add support for multi-tenancy

- auth_backends/__init__.py
- auth_backends/tests/mixins.py
- auth_backends/tests/test_views.py
- setup.py
This mixin can be used by the IDAs to test their implementations of the logout view.
ECOM-4607
> Moved logout view tests to mixin

- auth_backends/__init__.py
- auth_backends/backends.py
- auth_backends/tests/mixins.py
- auth_backends/tests/test_backends.py
- auth_backends/tests/test_views.py
- auth_backends/urls.py
- auth_backends/views.py
- test_settings.py
IDAs can now use this view, instead of making their own, to facilitate logouts.
ECOM-2345
> Added EdxOpenIdConnectLogoutView

- auth_backends/__init__.py
- setup.py
0.3.0 introduced a major breaking change, effectively [gutting PSA and moving its Django components to a new social-auth-app-django package](https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md#migrating-from-python-social-auth-to-split-social). We may require the new package at some point in the future, once it's stable.
@vkaracic @clintonb this will keep things building from scratch until we make the switch to the new, split-up PSA.
> Limit PSA to <0.3.0

- README.rst
- auth_backends/__init__.py
- auth_backends/backends.py
- auth_backends/tests/test_backends.py
This will allow us to use two different hosts for Docker-based devstack—one for user-facing authorization pages, another for server-to-server communication.
ECOM-6560
> Added support for a public URL root

- auth_backends/backends.py
- auth_backends/strategies.py
- auth_backends/tests/mixins.py
- auth_backends/tests/test_backends.py
- auth_backends/tests/test_strategies.py
- auth_backends/urls.py
- auth_backends/views.py
- setup.py
- test_settings.py
Installation of auth-backends now requires installation of a new PSA-affiliated package, social-auth-app-django.
@clintonb @vkaracic this is an alternative to https://github.com/edx/auth-backends/pull/27.
> Support PSA 0.3.0

- README.rst
- auth_backends/__init__.py
- auth_backends/backends.py
- auth_backends/strategies.py
- auth_backends/tests/test_backends.py
The upgrade from python-social-auth to social-core resulted in packages being moved. We missed this because we never tested the pipeline paths.
The README has also been updated to better reflect the steps needed to properly install this package.
LEARNER-693
> Corrected pipeline paths

- auth_backends/__init__.py
- auth_backends/strategies.py
The get_username creates a unique username by appending a UUID to the username from the ID token. This is not desirable since we need usernames to always be in sync with the authentication provider.
> Removed social_core.pipeline.user.get_username from EdxDjangoStrategy pipeline

- README.rst
- auth_backends/__init__.py
- auth_backends/backends.py
- auth_backends/tests/test_backends.py
This library update will be needed by ecommerce in order to get the lms user_id passed through appropriately.
IMPORTANT: This change requires https://github.com/edx/edx-platform/pull/20057 to land before we upgrade services, otherwise edx-platform will send invalid_scope errors.
Additionally, oauth applications are required to have access to the `user_id` scope in order for this not to break oAuth+SSO flow.  There is some follow-up work to ensure this is done for the apps using this flow (ecommerce, credentials, registrar).
ARCH-603
> ARCH-603: Retrieve and map user_id scope.

- auth_backends/backends.py
This PR will fix the anomaly when a staff user is also given superuser privileges. We expect that response data will contains details about `superuser` bit to indicate the superuser access level. If the bit is not provided in response, we assume it to be false. 
FYI -- @fysheets
> Fix anomaly between staff and superuser

- auth_backends/backends.py
- auth_backends/tests/test_backends.py
I'm converting one of our applications from OIDC to the OAuth2/JWT SSO backend, and encountered a regression.
During the SSO process, a unique `access_token` for each user gets saved in the `user_social_auths` `extra_data` field. However, that access token expires after one hour. With the OIDC provider, if the application wanted to get a new access token for the user in question, it could do so using the `refresh_token`, which was also stored in `extra_data`. (Or another option would be to start the SSO process over again, but that's slow, interrupts the user, and doesn't work in non-interactive contexts like backend celery workers.)
However, the OAuth2/JWT backend was not storing the `refresh_token` in `extra_data`. This PR fixes that, so that the refresh token will be stored.
Now, when …
> Store refresh_token in extra_data

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.rst
- README.rst
- auth_backends/docs/decisions/0001-use-changelog.rst
Post Merge:
- add CHANGELOG.rst
- add ADR for switching to CHANGELOG.rst
- add PR template
- add README instructions for releasing
ARCHBOM-1213
> ARCHBOM-1213: add changelog

- auth_backends/__init__.py
- requirements/base.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/test.txt
- requirements/travis.txt
**Description:**
downgraded the social-auth-core to stay at 3.2.0, relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1636)
> Downgraded social-auth-core to use 3.2.0

- auth_backends/__init__.py
- requirements/base.txt
- requirements/ci.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/test.txt
- setup.py
The bug mentioned on [ARCHBOM-1078](https://openedx.atlassian.net/browse/ARCHBOM-1078) is fixed in `social-auth-core==3.3.3`, See [this comment](https://openedx.atlassian.net/browse/BOM-2094?focusedCommentId=514498) for details, now we are unpinning it wherever it was previously pinned due to that bug.
Relevant JIRA : https://openedx.atlassian.net/browse/BOM-2187
> BOM-2187 : Unpin social-auth-core

- requirements/base.txt
- requirements/ci.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/test.txt
**Issue:** [BOM-2550](https://openedx.atlassian.net/browse/BOM-2550)
- `social-auth-core>=4.0.3` requires `PyJWT>=2.0.0` which conflicts with the current `PyJWT==1.7.1` constraint.
> BOM-2550: Pin social-auth-core<=4.0.3

- Makefile
- requirements/base.txt
- requirements/common_constraints.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/test.txt
Implemented common-constraint local sync. It gives us more control in case of different version implementation.
pip-tools gives error if two different versions of same package appears in make upgrade job. To fix this problem, added common constraint locally. It will always sync with web-url. With this approach this issue can be resolve.
> Sync common constraint locally to fix override version issue.

- CHANGELOG.rst
- Makefile
- auth_backends/__init__.py
- auth_backends/backends.py
- requirements/base.in
- requirements/base.txt
- requirements/common_constraints.txt
- requirements/constraints.txt
- requirements/dev.txt
- requirements/test.txt
In blockstore with latest version of pyjwt=2.1.0 this error appears.
`It is required that you pass in a value for the "algorithms" argument when calling decode().`
Its due to this change.
https://pyjwt.readthedocs.io/en/stable/changelog.html#dropped-deprecated-verify-expiration-param-in-jwt-decode
This PR constains major changes.
---------------------------
* **BREAKING CHANGE:** ``jwt.decode``: Inside ``EdXOAuth2::user_data`` Require explicit algorithms by default.
* **BREAKING CHANGE:** Upgraded dependency ``pyjwt[crypto]`` to 2.1.0, which introduces its own breaking changes that may affect consumers of this library. Pay careful attention to the 2.0.0 breaking changes documented in https://pyjwt.readthedocs.io/en/stable/changelog.html#v2-0-0.
> Latest version of pyjwt needs some critical changes.

- Makefile
- requirements/base.txt
- requirements/ci.txt
- requirements/common_constraints.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/test.txt
**Issue:** [BOM-2774](https://openedx.atlassian.net/browse/BOM-2774)
- https://github.com/edx/auth-backends/pull/125 upgraded the `pyjwt` package to the latest version in the repo.
- common_constraints has the constraint pyjwt<2.0.0 in them which conflicts with the latest version now required in the `base.in` so upgraded the condition to handle this constraint in the make upgrade step.
> BOM-2774: Fix the PyJwt common constraint handling

- .github/PULL_REQUEST_TEMPLATE.md
Remove `@edx/arch-review` from the list of required reviewers.
I added the PR template as part of adding a changelog 2 years ago,
and I don't see any reason to also have added a new review requirement,
namely `@edx/arch-review`. It is possible this was just copy/pasted.
Most contributors are already accustomed to asking owners for review
when and if there is any significant change that requires review. This
change simplifies the process for simple changes by not implying that
arch-review (which is not actually the owner anyway) needs to review.
**Description:**
Describe in a couple of sentences what this PR adds
**JIRA:**
[XXX-XXXX](https://openedx.atlassian.net/browse/XXX-XXXX)
**Additional Details**
* **Dependencies:**: List dependencies on other outstanding PRs, issues, etc.
* **Merge …
> fix: remove required reviewer from pr template

- requirements/base.txt
- requirements/ci.in
- requirements/ci.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/test.txt
- Codecov deprecated the pypi package long ago (Feb 2022) but left it up until now.
- Removing the package from requirements to fix the failing upgrade job.
- The Github Action we use to upload to codecov doesn’t depend on the package so our CI coverage won’t be affected by the change.
> fix: remove codecov from requirements

- requirements/base.txt
- requirements/ci.in
- requirements/ci.txt
- requirements/common_constraints.txt
- requirements/dev.txt
- requirements/pip-tools.txt
- requirements/pip.txt
- requirements/test.txt
- Removed `tox-battery` from requirements since it is not needed with `tox v4` anymore.
- Updated `tox` to `v4`.
> fix: remove tox-battery from requirements and update tox
