openedx/auth-backends

.travis.yml
=> Revert "travis bug with deployments on branches"

setup.py
=> Bump minimum PSA version

auth_backends/__init__.py, auth_backends/tests/test_views.py, auth_backends/views.py, test_settings.py
=> Added base logout view

README.rst, auth_backends/__init__.py, auth_backends/tests/test_views.py, auth_backends/urls.py, auth_backends/views.py, test_settings.py
We are duplicating this code across our repositories. This codifies those duplications into a single location.
ECOM-4607
=> Added login view and URL patterns

README.rst
=> Improved documentation for edX OIDC configuration

auth_backends/__init__.py, setup.py
0.2.20 includes an index on the Association model.
@clintonb @jibsheet @adampalay
=> Require at least PSA 0.2.20

auth_backends/__init__.py, setup.py
@edx/ecommerce @edx/devops FYI. ECOM-5259.
=> Bump minimum required version of PSA

README.rst, auth_backends/strategies.py, auth_backends/tests/test_strategies.py, test_settings.py
This strategy includes default settings that are standard across edX Django projects.
ECOM-6842
=> Created custom Python Social Auth strategy for Open edX

auth_backends/__init__.py, auth_backends/backends.py
user tracking id is added in https://github.com/edx/edx-platform/pull/14386
=> Added user tracking id.

auth_backends/__init__.py, setup.py
This will finally resolve the issues we have seen with usernames containing UUIDs.
LEARNER-998
=> Updated minimum versions of social-auth-core and social-auth-app-django

auth_backends/pipeline.py, auth_backends/strategies.py, auth_backends/tests/test_pipeline.py
social_core consider's email field protected and won't let it change, added a new pipeline function to update email address.
LEARNER-3013
=> Add pipeline function to update email address.

.travis.yml, AUTHORS, auth_backends/__init__.py, auth_backends/backends.py, auth_backends/strategies.py, auth_backends/tests/test_backends.py, tox.ini
For a hackathon J-N-T (Julia-Nimisha-Troy).
Also, bump version to 1.2.2
=> EdXOAuth2 supports the _PUBLIC_URL_ROOT backend setting.

auth_backends/backends.py
This is a Part#2 for https://github.com/edx/auth-backends/pull/61.
=> Add Superuser field in user data

auth_backends/__init__.py
I want to release the new changes in auth backends and this PR updates the version of auth-backends.
=> Create new Version for auth-backends for release

auth_backends/__init__.py, auth_backends/backends.py
Also, version bumped to 2.0.2.
This is part of the DOP->DOT migration.
---
This is required for hooking into the DOT SSO workflow in edx-analytics-dashboard (insights).
=> Add EdXOAuth2.auth_complete_signal on auth_complete()

HISTORY.rst
This was blocking validation on pypi.
=> Fix header in HISTORY.rst (and update date)

.travis.yml, HISTORY.rst, auth_backends/__init__.py, auth_backends/backends.py, auth_backends/pipeline.py, auth_backends/tests/mixins.py, auth_backends/views.py, requirements/base.in, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/pip-tools.txt, requirements/test.txt, requirements/travis.txt, setup.py, tox.ini
Relevant JIRA issue [here](https://openedx.atlassian.net/browse/BOM-1604).
=> Added support for python 3.8 and dropped support for older Django versions

openedx.yaml, requirements/base.txt, requirements/constraints.txt, requirements/dev.txt, requirements/pip-tools.txt, requirements/test.txt, requirements/travis.txt
https://openedx.atlassian.net/browse/ARCHBOM-1118
As part of our ownership initiative, mark that arch-bom is taking ownership of this library/repo.
=> Update ownership to arch-bom team.

README.rst
JIRA: https://openedx.atlassian.net/browse/BOM-2267
=> Fixed the build status link in README.rst

CHANGELOG.rst, auth_backends/__init__.py, auth_backends/backends.py, requirements/base.txt, requirements/ci.txt, requirements/constraints.txt, requirements/dev.txt, requirements/pip.txt, requirements/test.txt
Reverting pyjwt latest version. Causing issues in IDAs.
It was upgraded in this [PR](https://github.com/edx/auth-backends/pull/93)
=> Reverting pyjwt latest version. Causing issues in IDAs.

setup.py
Description:
Standardize the placement of version number
=> build: standardize version number placement
